-- MySQL Script generated by MySQL Workbench
-- lun. 29 mars 2021 18:05:25 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema base_create_culturel
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base_create_culturel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base_create_culturel` ;
-- -----------------------------------------------------
-- Schema bdd
-- -----------------------------------------------------
USE `base_create_culturel` ;

-- -----------------------------------------------------
-- Table `base_create_culturel`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Salle` (
  `IdSalle` INT NOT NULL AUTO_INCREMENT,
  `capacite` INT NOT NULL,
  PRIMARY KEY (`IdSalle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Evenement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Evenement` (
  `IdEvenement` INT NOT NULL AUTO_INCREMENT,
  `NomEvent` VARCHAR(45) NOT NULL,
  `TypeEvent` VARCHAR(45) NOT NULL,
  `DateDebEvent` DATE NOT NULL,
  `DateFinEvent` DATE NOT NULL,
  `HeureDebEvent` TIME NOT NULL,
  `HeureFinEvent` TIME NOT NULL,
  `EtatEvent` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdEvenement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Artiste`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Artiste` (
  `idArtiste` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArtiste`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Spectacle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Spectacle` (
  `IdSpectacle` INT NOT NULL AUTO_INCREMENT,
  `IdEvenement` INT NOT NULL,
  `IdSalle` INT NOT NULL,
  `IdArtiste` INT NOT NULL,
  `NomSpectacle` VARCHAR(45) NOT NULL,
  `DateSpectacle` DATE NOT NULL,
  `HeureDebut` TIME NOT NULL,
  `HeureFin` TIME NOT NULL,
  `TypeSpectacle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdSpectacle`),
  INDEX `IdSalle_Spectacle_idx` (`IdSalle` ASC) VISIBLE,
  INDEX `IdEvenement_Spectacle_idx` (`IdEvenement` ASC) VISIBLE,
  INDEX `IdArtiste_Spectacle_idx` (`IdArtiste` ASC) VISIBLE,
  CONSTRAINT `IdSalle_Spectacle`
    FOREIGN KEY (`IdSalle`)
    REFERENCES `base_create_culturel`.`Salle` (`IdSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdEvenement_Spectacle`
    FOREIGN KEY (`IdEvenement`)
    REFERENCES `base_create_culturel`.`Evenement` (`IdEvenement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdArtiste_Spectacle`
    FOREIGN KEY (`IdArtiste`)
    REFERENCES `base_create_culturel`.`Artiste` (`idArtiste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Tarif`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Tarif` (
  `NomTarif` VARCHAR(45) NOT NULL,
  `PrixTarif` FLOAT NOT NULL,
  PRIMARY KEY (`NomTarif`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Reservation` (
  `IdReservation` INT NOT NULL AUTO_INCREMENT,
  `IdSpectacle` INT NOT NULL,
  `Compte` VARCHAR(45) NOT NULL,
  `DateReservation` DATE NOT NULL,
  PRIMARY KEY (`IdReservation`),
  INDEX `IdSpectacle_Reservation_idx` (`IdSpectacle` ASC) VISIBLE,
  CONSTRAINT `IdSpectacle_Reservation`
    FOREIGN KEY (`IdSpectacle`)
    REFERENCES `base_create_culturel`.`Spectacle` (`IdSpectacle`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Paiement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Paiement` (
  `IdPaiement` INT NOT NULL,
  `IdReservation` INT NULL,
  `NomTarif` VARCHAR(45) NOT NULL,
  `LieuPaiement` VARCHAR(45) NOT NULL,
  `DatePaiement` DATE NOT NULL,
  `HeurePaiement` TIME NOT NULL,
  `IdSpectacle` INT NOT NULL,
  PRIMARY KEY (`IdPaiement`),
  INDEX `NomTarif_Paiement_idx` (`NomTarif` ASC) VISIBLE,
  INDEX `IdReservation_Paiement_idx` (`IdReservation` ASC) VISIBLE,
  INDEX `IdSpectacle_idx` (`IdSpectacle` ASC) VISIBLE,
  CONSTRAINT `NomTarif_Paiement`
    FOREIGN KEY (`NomTarif`)
    REFERENCES `base_create_culturel`.`Tarif` (`NomTarif`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `IdReservation_Paiement`
    FOREIGN KEY (`IdReservation`)
    REFERENCES `base_create_culturel`.`Reservation` (`IdReservation`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `IdSpectacle_Paiement`
    FOREIGN KEY (`IdSpectacle`)
    REFERENCES `base_create_culturel`.`Spectacle` (`IdSpectacle`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Remboursement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Remboursement` (
  `IdPaiement` INT NOT NULL,
  `IdEvenement` INT NOT NULL,
  `EtatRemboursement` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdPaiement`, `IdEvenement`),
  INDEX `IdEvenement_Remboursement_idx` (`IdEvenement` ASC) VISIBLE,
  CONSTRAINT `IdPaiement_Remboursement`
    FOREIGN KEY (`IdPaiement`)
    REFERENCES `base_create_culturel`.`Paiement` (`IdPaiement`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `IdEvenement_Remboursement`
    FOREIGN KEY (`IdEvenement`)
    REFERENCES `base_create_culturel`.`Evenement` (`IdEvenement`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Cachet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Cachet` (
  `IdCachet` INT NOT NULL AUTO_INCREMENT,
  `IdArtiste` INT NOT NULL,
  `IdSpectacle` INT NOT NULL,
  `DateCachet` DATE NOT NULL,
  `EtatCachet` VARCHAR(45) NOT NULL,
  `MontantCachet` FLOAT NOT NULL,
  PRIMARY KEY (`IdCachet`),
  INDEX `IdArtiste_Cachet_idx` (`IdArtiste` ASC) VISIBLE,
  INDEX `IdSpectacle_Cachet_idx` (`IdSpectacle` ASC) VISIBLE,
  CONSTRAINT `IdArtiste_Cachet`
    FOREIGN KEY (`IdArtiste`)
    REFERENCES `base_create_culturel`.`Artiste` (`idArtiste`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `IdSpectacle_Cachet`
    FOREIGN KEY (`IdSpectacle`)
    REFERENCES `base_create_culturel`.`Spectacle` (`IdSpectacle`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Personne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Personne` (
  `IdPersonne` INT NOT NULL AUTO_INCREMENT,
  `Responsable` INT NULL,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `DateNaissance` DATE NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `Telephone` INT NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Job` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdPersonne`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`InscriptionBenevole`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`InscriptionBenevole` (
  `IdInscription` INT NOT NULL AUTO_INCREMENT,
  `IdPersonne` INT NOT NULL,
  `IdEvenement` INT NOT NULL,
  PRIMARY KEY (`IdInscription`),
  INDEX `IdEvenement_Inscription_idx` (`IdEvenement` ASC) VISIBLE,
  INDEX `IdPersonne_Inscription_idx` (`IdPersonne` ASC) VISIBLE,
  CONSTRAINT `IdPersonne_Inscription`
    FOREIGN KEY (`IdPersonne`)
    REFERENCES `base_create_culturel`.`Personne` (`IdPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IdEvenement_Inscription`
    FOREIGN KEY (`IdEvenement`)
    REFERENCES `base_create_culturel`.`Evenement` (`IdEvenement`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Participation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Participation` (
  `IdParticipation` INT NOT NULL AUTO_INCREMENT,
  `IdInscription` INT NOT NULL,
  `Responsable` INT NULL UNIQUE,
  PRIMARY KEY (`IdParticipation`),
  INDEX `IdInscription_Participation_idx` (`IdInscription` ASC) VISIBLE,
  CONSTRAINT `IdInscription_Participation`
    FOREIGN KEY (`IdInscription`)
    REFERENCES `base_create_culturel`.`InscriptionBenevole` (`IdPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Salaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Salaire` (
  `IdPersonne` INT NOT NULL,
  `AnneeSalaire` YEAR(4) NOT NULL,
  `Salaire` FLOAT NOT NULL,
  PRIMARY KEY (`IdPersonne`, `AnneeSalaire`),
  CONSTRAINT `IdPersonne_Salaire`
    FOREIGN KEY (`IdPersonne`)
    REFERENCES `base_create_culturel`.`Personne` (`IdPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_create_culturel`.`Specifique`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_create_culturel`.`Specifique` (
  `idSpecifique` INT NOT NULL AUTO_INCREMENT,
  `IdPersonne` INT NOT NULL,
  `Fonction` VARCHAR(45) NOT NULL,
  `Responsable` INT NULL UNIQUE,
  PRIMARY KEY (`idSpecifique`),
  INDEX `IdPersonne_Specifique_idx` (`IdPersonne` ASC) VISIBLE,
  CONSTRAINT `IdPersonne_Specifique`
    FOREIGN KEY (`IdPersonne`)
    REFERENCES `base_create_culturel`.`Personne` (`IdPersonne`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
